<?php

function sum_menu() {
  $items['sum'] = array(
    'title' => 'Calculate',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sum_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['sum_success_page'] = array(
    'title' => 'Success',
    'page callback' => 'sum_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function sum_form() {
  $form['left_number'] = array(
    '#title' => 'Left Number',
    '#type' => 'textfield',
    '#description' => t('Please enter first number'),
    '#element_validate' => array('element_validate_integer', 'element_validate_range'),
    '#required' => TRUE,
  );
  $form['right_number'] = array(
    '#title' => 'Right Number',
    '#type' => 'textfield',
    '#description' => t('Please enter second number'),
    '#element_validate' => array('element_validate_integer', 'element_validate_range'),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => "get it",
  );
  return $form;
}

function sum_form_submit($form, &$form_state) {
  $sum = $form_state['values']['left_number'] + $form_state['values']['right_number'];
  $_SESSION['sum_output'] = $sum;
  $form_state['redirect'] = 'sum_success_page';

}

function sum_success(){
  $sum =$_SESSION['sum_output'];
  return "sum is ". $sum;
}
function element_validate_range($element) {
  if ($element['#value'] >= 100 || $element['#value'] <= 0) {
    form_error($element, t('fuck you buddy'));
  }
}
